# Generated by Django 5.1.15 on 2026-09-01 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.examen')),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postulantes.inscripcion')),
            ],
        ),
    ]
