# Generated by Django 5.2.17 on 2026-09-17 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def asignar_numeros_postulacion_existentes(apps, schema_editor):
    """Genera un N.° de postulación para las inscripciones que ya existían
    antes de este cambio, antes de exigir que el campo sea único."""
    Inscripcion = apps.get_model('postulantes', 'Inscripcion')
    contadores_por_anio = {}
    for inscripcion in Inscripcion.objects.order_by('fecha_inscripcion'):
        anio = inscripcion.fecha_inscripcion.year if inscripcion.fecha_inscripcion else 2026
        contadores_por_anio[anio] = contadores_por_anio.get(anio, 0) + 1
        inscripcion.numero_postulacion = f"POST-{anio}-{contadores_por_anio[anio]:05d}"
        inscripcion.save(update_fields=['numero_postulacion'])


def revertir_numeros_postulacion(apps, schema_editor):
    """No hay nada que deshacer: al bajar la migración se elimina el campo."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("convocatorias", "0001_initial"),
        ("postulantes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documento",
            options={"ordering": ["tipo"]},
        ),
        migrations.AlterModelOptions(
            name="inscripcion",
            options={"ordering": ["-fecha_inscripcion"]},
        ),
        migrations.AddField(
            model_name="documento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente_revision", "Pendiente de revisión"),
                    ("validado", "Validado"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente_revision",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="fecha_revision",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documento",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="documento",
            name="revisado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_revisados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="numero_postulacion",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.RunPython(
            asignar_numeros_postulacion_existentes,
            revertir_numeros_postulacion,
        ),
        migrations.AlterField(
            model_name="inscripcion",
            name="numero_postulacion",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AddField(
            model_name="postulante",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="fotos_postulantes/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="postulante",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("femenino", "Femenino"),
                    ("masculino", "Masculino"),
                    ("otro", "Otro"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("cedula", "Cédula de identidad"),
                    ("certificado_votacion", "Certificado de votación"),
                    ("acta_grado", "Acta de grado / Título de bachiller"),
                    ("foto", "Foto tamaño carnet"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="inscripcion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("docs_pendientes", "Documentos pendientes"),
                    ("en_revision", "En revisión"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                ],
                default="docs_pendientes",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inscripcion",
            name="postulante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscripciones",
                to="postulantes.postulante",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documento",
            unique_together={("inscripcion", "tipo")},
        ),
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together={("postulante", "convocatoria")},
        ),
    ]
