# Generated by Django 5.2.17 on 2026-09-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0004_inscripcion_comentario_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='pasos_marcados',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos_postulantes/%Y/%m/'),
        ),
    ]
