# Generated by Django 5.2.17 on 2026-09-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0005_inscripcion_pasos_marcados_alter_postulante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='nombres',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
