# Generated by Django 5.2.17 on 2026-09-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0006_alter_postulante_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('docs_pendientes', 'Documentos pendientes'), ('en_revision', 'En revisión'), ('aprobada', 'Revisada'), ('rechazada', 'Rechazada')], default='docs_pendientes', max_length=20),
        ),
    ]
