# Generated by Django 5.2.17 on 2026-09-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0007_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='Sigue los pasos de tu proceso de admisión. En cada paso marca que ya lo realizaste y sube tu documento; verás un ✓ cuando esté listo. Si admisión rechaza un documento, verás el motivo y podrás subirlo de nuevo.', verbose_name='Texto de introducción')),
                ('paso1_nombre', models.CharField(default='Registro', max_length=40, verbose_name='Nombre del paso 1')),
                ('paso1_documento', models.CharField(default='Certificado de registro', max_length=80, verbose_name='Documento del paso 1')),
                ('paso1_ayuda', models.TextField(blank=True, verbose_name='Indicaciones del paso 1')),
                ('paso2_nombre', models.CharField(default='Inscripción', max_length=40, verbose_name='Nombre del paso 2')),
                ('paso2_documento', models.CharField(default='Certificado de inscripción', max_length=80, verbose_name='Documento del paso 2')),
                ('paso2_ayuda', models.TextField(blank=True, verbose_name='Indicaciones del paso 2')),
                ('paso3_nombre', models.CharField(default='Evaluación', max_length=40, verbose_name='Nombre del paso 3')),
                ('paso3_documento', models.CharField(default='Evaluación (nota obtenida)', max_length=80, verbose_name='Documento del paso 3')),
                ('paso3_ayuda', models.TextField(blank=True, verbose_name='Indicaciones del paso 3')),
                ('paso4_nombre', models.CharField(default='Postulación', max_length=40, verbose_name='Nombre del paso 4')),
                ('paso4_documento', models.CharField(default='Registro de postulación a la carrera', max_length=80, verbose_name='Documento del paso 4')),
                ('paso4_ayuda', models.TextField(blank=True, verbose_name='Indicaciones del paso 4')),
                ('paso5_nombre', models.CharField(default='Aceptación', max_length=40, verbose_name='Nombre del paso 5')),
                ('paso5_documento', models.CharField(default='Certificado de aceptación del cupo', max_length=80, verbose_name='Documento del paso 5')),
                ('paso5_ayuda', models.TextField(blank=True, verbose_name='Indicaciones del paso 5')),
            ],
            options={
                'verbose_name': 'configuración del proceso',
                'verbose_name_plural': 'configuración del proceso',
            },
        ),
    ]
