# Generated by Django 5.2.17 on 2026-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0009_uniqueconstraint_inscripcion_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialInscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar', models.BooleanField(default=True, verbose_name='Mostrar el botón del tutorial a los postulantes')),
                ('titulo', models.CharField(default='Tutorial de matriculación', max_length=120, verbose_name='Título')),
                ('video_url', models.URLField(blank=True, help_text='Pega el enlace del video de YouTube con el paso a paso de la matriculación.', verbose_name='Enlace del video de YouTube')),
                ('descripcion', models.TextField(blank=True, default='En este video te explicamos, paso a paso, cómo realizar tu matriculación en el ISTAM.', verbose_name='Explicación del tutorial')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tutorial de matriculación',
                'verbose_name_plural': 'tutorial de matriculación',
            },
        ),
    ]
